# Airsense - Environmental Monitoring Platform
runtime: nodejs18
env: standard

env_variables:
  NODE_ENV: "production"
  PORT: "8080"
  MONGODB_URI: "mongodb+srv://Henode:PasswordUserdb@cluster0.q0vzejg.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0&tlsAllowInvalidCertificates=true"
  MONGODB_DB: "environmental_data"
  MONGODB_COLLECTION: "datasets"
  OPENWEATHER_API_KEY: "a25037f6d8ef17f96b08a597d1716fa4"

handlers:
  # Server API routes
  - url: /api/.*
    script: auto
    secure: always
  
  # Client static files
  - url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|svg|json|woff|woff2|ttf|eot))$
    static_files: dist/\1
    upload: dist/.*\.(js|css|png|jpg|jpeg|gif|ico|svg|json|woff|woff2|ttf|eot)$
    secure: always

  # Client catch-all route
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always

instance_class: F2

automatic_scaling:
  min_instances: 1
  max_instances: 3
  min_idle_instances: 1
  min_pending_latency: 30ms
  max_concurrent_requests: 50

# File exclusions
skip_files:
- ^node_modules$
- ^.env$
- ^\.git$
- ^\.github$
