# AirSense Frontend - Static Build
runtime: python39  # Using Python runtime for static files

service: frontend

handlers:
  # Serve all static files with URL ending with extensions
  - url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|svg|json|woff|woff2|ttf|eot))$
    static_files: dist/\1
    upload: dist/.*\.(js|css|png|jpg|jpeg|gif|ico|svg|json|woff|woff2|ttf|eot)$
    secure: always
  
  # Catch all handler to index.html
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always

# No environment variables needed for static files