# AirSense - Environmental Monitoring Platform
runtime: nodejs20

env_variables:
  NODE_ENV: "production"
  MONGODB_URI: ${MONGODB_URI}
  MONGODB_DB: ${MONGODB_DB}
  MONGODB_COLLECTION: ${MONGODB_COLLECTION}
  OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY}
  GEMINI_API_KEY: ${GEMINI_API_KEY}  # Replace with your actual Gemini API key before deployment

handlers:
  # API Routes
  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  min_instances: 1
  max_instances: 5
  min_idle_instances: 1
  min_pending_latency: 30ms
  max_concurrent_requests: 50